name: Deploy
on: 
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setting_up_pip
        run : python -m pip install --upgrade pip
      - name: Install
        run : pip install . --no-binary :all:
      - name: Build
        run : auto_fast_docs ${{github.event.repository.name}} --username ${{github.actor}} --layout flat
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./site