name: Deploy
on: 
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install
        run : | 
          python -m pip install --upgrade pip
          pip install .
      - name: Build
        run : auto_fast_docs ${{github.event.repository.name}} --username ${{github.actor}} --layout flat